# Generated by Django 5.2 on 2025-07-13 18:04

import prosses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prosses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fiche_descptive",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="fiche_descptive",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=prosses.models.user_directory_path
            ),
        ),
    ]
