# Generated by Django 5.2 on 2025-07-19 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "modules_studets",
            "0004_alter_affectation_options_alter_affectation_filiere_and_more",
        ),
        ("prosses", "0002_rename_name_fiche_descptive_title_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Files_affectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "afectation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules_studets.affectation",
                    ),
                ),
                (
                    "filche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prosses.fiche_descptive",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules_studets.filers_modules",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
