# Generated by Django 5.2 on 2025-07-20 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filers", "0002_alter_filieres_title"),
        (
            "modules_studets",
            "0004_alter_affectation_options_alter_affectation_filiere_and_more",
        ),
        ("prosses", "0003_files_affectation"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiche_descptive",
            name="filer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="filers.filieres",
            ),
        ),
        migrations.AddField(
            model_name="fiche_descptive",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="modules_studets.filers_modules",
            ),
        ),
        migrations.DeleteModel(
            name="Files_affectation",
        ),
    ]
