# Generated by Django 5.2 on 2025-07-20 12:30

from django.db import migrations, models

import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("prosses", "0004_fiche_descptive_filer_fiche_descptive_module_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiche_descptive",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
