# Generated by Django 5.2 on 2025-07-20 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prosses", "0005_fiche_descptive_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiche_descptive",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
