# Generated by Django 5.2 on 2025-07-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acountes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="imge",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/users/<property object at 0x000002A1C1670680>/",
            ),
        ),
    ]
