# Generated by Django 5.2 on 2025-07-13 18:09

import acountes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acountes", "0002_customuser_imge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="imge",
            field=models.FileField(
                blank=True, null=True, upload_to=acountes.models.user_directory_path
            ),
        ),
    ]
