# Generated by Django 5.2 on 2025-07-13 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("filers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filers_modules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titer_module", models.CharField(max_length=11, unique=True)),
                ("referance_uf", models.CharField(max_length=11, unique=True)),
                (
                    "filere",
                    models.ManyToManyField(
                        related_name="filers_modules", to="filers.filieres"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seaquesnces_modules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nbr_sequence", models.IntegerField()),
                ("titer_sequence", models.CharField(max_length=11, unique=True)),
                ("total_hores", models.IntegerField()),
                ("all_sequences_details", models.TextField()),
                (
                    "module",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules_studets.filers_modules",
                    ),
                ),
            ],
        ),
    ]
