# Generated by Django 5.2 on 2025-07-16 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filers", "0002_alter_filieres_title"),
        ("modules_studets", "0002_filers_modules_formater"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filers_modules",
            name="formater",
        ),
        migrations.RemoveField(
            model_name="seaquesnces_modules",
            name="all_sequences_details",
        ),
        migrations.RemoveField(
            model_name="seaquesnces_modules",
            name="nbr_sequence",
        ),
        migrations.AddField(
            model_name="filers_modules",
            name="heraire_totale",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="filers_modules",
            name="nbr_sequence",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="filers_modules",
            name="titer_module_pransipale",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="seaquesnces_modules",
            name="objectif_sequence",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="filers_modules",
            name="referance_uf",
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name="filers_modules",
            name="titer_module",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="seaquesnces_modules",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sequences",
                to="modules_studets.filers_modules",
            ),
        ),
        migrations.AlterField(
            model_name="seaquesnces_modules",
            name="titer_sequence",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="seaquesnces_modules",
            name="total_hores",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Chapitres_sequenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("duree", models.IntegerField(default=0)),
                (
                    "sequenses",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapitres",
                        to="modules_studets.seaquesnces_modules",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Affectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filers.filieres",
                    ),
                ),
                (
                    "formateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modules",
                    models.ManyToManyField(
                        related_name="affectations", to="modules_studets.filers_modules"
                    ),
                ),
            ],
            options={
                "unique_together": {("formateur", "filiere")},
            },
        ),
    ]
