# Generated by Django 5.2 on 2025-07-16 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filers", "0002_alter_filieres_title"),
        ("modules_studets", "0003_remove_filers_modules_formater_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="affectation",
            options={
                "verbose_name": "Affectation",
                "verbose_name_plural": "Affectations",
            },
        ),
        migrations.AlterField(
            model_name="affectation",
            name="filiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="filers.filieres",
                verbose_name="Filière",
            ),
        ),
        migrations.AlterField(
            model_name="affectation",
            name="formateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Formateur",
            ),
        ),
        migrations.AlterField(
            model_name="affectation",
            name="modules",
            field=models.ManyToManyField(
                related_name="affectations",
                to="modules_studets.filers_modules",
                verbose_name="Modules affectés",
            ),
        ),
        migrations.AlterField(
            model_name="chapitres_sequenses",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="chapitres_sequenses",
            name="duree",
            field=models.PositiveIntegerField(default=0, verbose_name="Durée (min)"),
        ),
        migrations.AlterField(
            model_name="chapitres_sequenses",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="chapitres_sequenses",
            name="sequenses",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapitres",
                to="modules_studets.seaquesnces_modules",
                verbose_name="Séquence",
            ),
        ),
        migrations.AlterField(
            model_name="chapitres_sequenses",
            name="titre",
            field=models.CharField(max_length=255, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="filers_modules",
            name="filere",
            field=models.ManyToManyField(
                related_name="filers_modules",
                to="filers.filieres",
                verbose_name="Filières",
            ),
        ),
        migrations.AlterField(
            model_name="filers_modules",
            name="heraire_totale",
            field=models.PositiveIntegerField(default=0, verbose_name="Heures totales"),
        ),
        migrations.AlterField(
            model_name="filers_modules",
            name="nbr_sequence",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre de séquences"
            ),
        ),
        migrations.AlterField(
            model_name="filers_modules",
            name="referance_uf",
            field=models.CharField(
                max_length=25, unique=True, verbose_name="Référence UF"
            ),
        ),
        migrations.AlterField(
            model_name="filers_modules",
            name="titer_module",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Titre du module"
            ),
        ),
        migrations.AlterField(
            model_name="filers_modules",
            name="titer_module_pransipale",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre principal"
            ),
        ),
        migrations.AlterField(
            model_name="seaquesnces_modules",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sequences",
                to="modules_studets.filers_modules",
                verbose_name="Module",
            ),
        ),
        migrations.AlterField(
            model_name="seaquesnces_modules",
            name="objectif_sequence",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Objectif"
            ),
        ),
        migrations.AlterField(
            model_name="seaquesnces_modules",
            name="titer_sequence",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Titre de la séquence"
            ),
        ),
        migrations.AlterField(
            model_name="seaquesnces_modules",
            name="total_hores",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total des heures"
            ),
        ),
        migrations.CreateModel(
            name="AffectationSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "affectation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequences",
                        to="modules_studets.affectation",
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules_studets.seaquesnces_modules",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affectation Séquence",
                "verbose_name_plural": "Affectations Séquences",
                "unique_together": {("affectation", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="AffectationChapitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chapitre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modules_studets.chapitres_sequenses",
                    ),
                ),
                (
                    "affectation_sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapitres",
                        to="modules_studets.affectationsequence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affectation Chapitre",
                "verbose_name_plural": "Affectations Chapitres",
                "unique_together": {("affectation_sequence", "chapitre")},
            },
        ),
    ]
