# Generated by Django 5.2 on 2025-07-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "modules_studets",
            "0004_alter_affectation_options_alter_affectation_filiere_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="seaquesnces_modules",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
    ]
