# Generated by Django 5.2.4 on 2025-07-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_studets', '0005_seaquesnces_modules_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitres_sequenses',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chapitres_sequenses',
            name='duree',
        ),
    ]
