# Generated by Django 5.2 on 2025-07-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filieres",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
